---
- include_role:
    name: computate.computate_luajit
- name: "Install dependencies as root: {{ APP_DEPENDENCIES | join(' ') }}"
  package:
    name: "{{ APP_DEPENDENCIES }}"
  become: true
  register: INSTALL_DEPENDENCIES
  ignore_errors: true
- name: "Install dependencies as user {{ APP_USER }}: {{ APP_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }} | true"
  loop: "{{ APP_DEPENDENCIES }}"
  when: INSTALL_DEPENDENCIES.failed

# irrlicht dependency
- name: "Check for the README file {{ IRRLICHT_README }}"
  stat:
    path: "{{ IRRLICHT_README }}"
  register: IRRLICHT_README_PATH
- name: "Clone the {{ IRRLICHT_REPO }} source code into {{ IRRLICHT_SRC }}"
  git:
    repo: "{{ IRRLICHT_REPO }}"
    dest: "{{ IRRLICHT_SRC }}"
    version: "{{ IRRLICHT_TAG }}"
  when: not IRRLICHT_README_PATH.stat.exists
- name: "Run the cmake script in {{ IRRLICHT_SRC }}"
  shell:
    cmd: "cmake .  -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX={{ APP_PREFIX }}"
    chdir: "{{ IRRLICHT_SRC }}"
- name: "Run the make script in {{ IRRLICHT_SRC }}: make -j $(nproc)"
  shell:
    cmd: make -j $(nproc)
    chdir: "{{ IRRLICHT_SRC }}"
- name: "Run the make install script in {{ IRRLICHT_SRC }}"
  shell:
    cmd: make install
    chdir: "{{ IRRLICHT_SRC }}"

# minetest
- name: "Create the directory {{ APP_SRC }}"
  file:
    name: "{{ APP_SRC }}"
    state: directory
- name: "Check for the README file {{ APP_README }}"
  stat:
    path: "{{ APP_README }}"
  register: APP_README_PATH
- name: "Clone the {{ APP_REPO }} source code into {{ APP_SRC }}"
  git:
    repo: "{{ APP_REPO }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  when: not APP_README_PATH.stat.exists
- name: "Run the cmake script in {{ APP_SRC }}"
  shell:
    cmd: "cmake .  -DRUN_IN_PLACE=TRUE -DCMAKE_INSTALL_PREFIX={{ APP_PREFIX }}"
    chdir: "{{ APP_SRC }}"
- name: "Run the make script in {{ APP_SRC }}: make -j $(nproc)"
  shell:
    cmd: make -j $(nproc)
    chdir: "{{ APP_SRC }}"
- name: "Run the make install script in {{ APP_SRC }}: make install -j $(nproc)"
  shell:
    cmd: make install -j $(nproc)
    chdir: "{{ APP_SRC }}"
- name: "Create the launcher {{ APP_DESKTOP }}"
  template:
    src: app.desktop
    dest: "{{ APP_DESKTOP }}"

###########
# Plugins #
###########

- name: "Clone the Minetest Game game source code into {{ APP_SRC }}/games"
  git:
    repo: "git@github.com:minetest/minetest_game.git"
    dest: "{{ APP_PREFIX }}/games/minetest_game"
    version: "5.4.1"
- name: "Clone the MineClone2 game source code into {{ APP_SRC }}/games"
  git:
    repo: "git@github.com:SonicTheCrafter/MineClone2.git"
    dest: "{{ APP_PREFIX }}/games/MineClone2"
- name: "Clone the Bountiful Blossoms Halcyon Days game source code into {{ APP_SRC }}/games"
  git:
    repo: "git@github.com:azekillDIABLO/Bountiful-Blossoms-Halcyon-Days.git"
    dest: "{{ APP_PREFIX }}/games/Bountiful-Blossoms-Halcyon-Days"

- name: "Clone the worldedit mod source code into {{ APP_SRC }}/mods"
  git:
    repo: "git@github.com:Uberi/Minetest-WorldEdit.git"
    dest: "{{ APP_PREFIX }}/mods/Minetest-WorldEdit-1.3"
    version: "1.3"

